Feature/header/chakra
hiromuota166/kuromalun pull request #11
Opened 2024-05-01 14:29 UTC by hiromuota166

2024-05-01 15:12 UTC, shivasaki requested changes

2024-05-01 15:16 UTC, hiromuota166 commented on kuromalun-front/next.config.mjs
`GET /_next/static/chunks/app/index.mjs.map 404 in 956ms`
このエラー直そうとして一回書いたら治った気がしたけど結局治ってないんで消しますね。

2024-05-01 15:29 UTC, shivasaki requested changes
細かいけどお願い🙏

2024-05-01 15:29 UTC, shivasaki commented on kuromalun-front/tailwind.config.ts
ごめんなさい、書き方悪かった
snake_caseよりcamelCaseが良いのではないか
多分バグとかはないけどjs/tsの慣習なのと、エレメントのクラス名と間違えたりしそうとか、何か意味があるのかと思ってしまうとかは考えられる

2024-05-02 01:53 UTC, shivasaki approved these changes
LGTM!

2024-05-02 01:54 UTC, merged