Ping-Pong-app
hiromuota166/kuromalun pull request #16
Opened 2024-05-04 07:34 UTC by Chiro358

/Ping-Pong/でリクエストボディにstr型の"Ping"を送信するとJSONでメッセージ"Pong"が返って来る。

2024-05-05 06:57 UTC, hiromuota166 commented on kuromalun-back/Ping-Pong.py
Python のファイル名は、拡張子は .py で、できるだけ短いほうがよく、単語をつなげるときはスネークケースを使います。ハイフン - は使ってはいけません。
https://python.softmoco.com/basics/python-naming-conventions.php

2024-05-07 11:07 UTC, shivasaki commented on kuromalun-back/Ping_Pong.py
コミットメッセージに即してない作業なので本来は分けてコミットできるといいですね
めんどいので今回はこのまま

2024-05-07 11:09 UTC, shivasaki requested changes

2024-05-07 11:09 UTC, shivasaki commented on kuromalun-back/__pycache__/Ping_Pong.cpython-310.pyc
後からで申し訳ないんやけどgitignoreもうちょい書いてほしい🙏
このファイルはいつかrebaseで消すので設定の更新をお願いします

参考: https://github.com/github/gitignore/blob/main/Python.gitignore

2024-05-07 11:10 UTC, shivasaki reviewed
ここのコミットって何してますか？
必要なければ履歴ごと消したい

2024-05-08 00:03 UTC, Chiro358 commented
> ここのコミットって何してますか？ 必要なければ履歴ごと消したい
> 
> [35af857](https://github.com/hiromuota166/kuromalun/commit/35af85735a1c2004e2eba77b71d7fefb2406495b)

多分消していいやつです

2024-05-08 00:05 UTC, Chiro358 commented
とりあえず__pycache__を追加しました

2024-05-08 02:53 UTC, shivasaki commented
> > ここのコミットって何してますか？ 必要なければ履歴ごと消したい
> > [35af857](https://github.com/hiromuota166/kuromalun/commit/35af85735a1c2004e2eba77b71d7fefb2406495b)
> 
> 多分消していいやつです

これ僕が先にgitkeep消す処理を追加したけどあとから @Chiro358 がそれをpullせず同じことしちゃって分岐したんですね。それで変更がないように見えました。
作業前に履歴が古くないか確かめるのと、同じブランチで変更加えたら注意喚起するべきでした。

2024-05-08 08:38 UTC, shivasaki approved these changes

2024-05-08 08:38 UTC, merged