8 circledetail page
hiromuota166/kuromalun pull request #25
Opened 2024-05-09 22:40 UTC by hiromuota166

## チェックリスト
- circleCreateDetailEdit画面とcircleDetail画面を作りました。
- とりあえずUIを作って他の画面に移行したいのでページにCSSベッタベタに書きました。
- [ ] レスポンシブデザインになっているか

##circleCreateEdit
![image](https://github.com/hiromuota166/kuromalun/assets/131576261/8bacd67a-8f98-4e2d-b25b-dd017f361cb9)
![image](https://github.com/hiromuota166/kuromalun/assets/131576261/ff7b7651-9a35-4fb3-b430-ed1131d86ba8)

##circleDetail
![image](https://github.com/hiromuota166/kuromalun/assets/131576261/9b50ec3e-d9c7-4fe4-af84-af1a373a4f14)
![image](https://github.com/hiromuota166/kuromalun/assets/131576261/51b652fa-f295-461f-b502-9dc2e6624197)

2024-05-12 11:49 UTC, hiromuota166 commented
レビューお願いします
@shivasaki  @Chiro358

2024-05-14 04:28 UTC, shivasaki reviewed
`Axios.ts`は使わないのであればなくていいですね

2024-05-14 05:01 UTC, shivasaki requested changes

2024-05-14 05:25 UTC, shivasaki requested changes

2024-05-14 05:25 UTC, shivasaki commented on kuromalun-front/src/components/CircleInputText.tsx
IMO: ここもキャメルケースかなー

2024-05-14 09:09 UTC, hiromuota166 commented
> `Axios.ts`は使わないのであればなくていいですね

こういう場合は無視か消すかどちらがいいですか？

2024-05-14 09:37 UTC, shivasaki commented
> > `Axios.ts`は使わないのであればなくていいですね
> 
> こういう場合は無視か消すかどちらがいいですか？

これはレビューじゃなくてコメントなので何もしなくていいです
プレフィックス忘れてた

2024-05-15 00:29 UTC, hiromuota166 commented
問題点なければapproveお願いします

2024-05-17 01:41 UTC, shivasaki approved these changes
LGTMです

<img width="375" alt="image" src="https://github.com/hiromuota166/kuromalun/assets/20058094/354fb4e5-c118-4ffa-a1d6-bac6f66ac94d">

<img width="361" alt="image" src="https://github.com/hiromuota166/kuromalun/assets/20058094/f7f14c9f-deb9-4c35-b65f-dccc1333a49e">

2024-05-17 01:41 UTC, merged